### ISSUE TITLE
Stupid question...

### ISSUE THREAD

**Issue by seenickcode** [azavea/ansible-buildkite-agent#75]
How does one use this repo? It doesn't seem to be installable via Galaxy (either providing the repo URL or a local git repo).

**Comment by bombsimon** [comment]
I have a `requirements.yaml` file which looks like this:

```yaml
---
roles:
  - src: https://github.com/improbable-eng/ansible-buildkite-agent
    version: develop
    name: ansible-buildkite-agent
```

And then I use `ansible-galaxy` like this:

```sh
ansible-galaxy role install -r /path/to/requirements.yaml
```
